title: Towards Autonomous Caretakers via Procedure-based Automation
description: |-
  Michael W. Lanighan and Ana Huaman Quispe and Seth Gee and David Kortenkamp
  IEEE iSpaRo 2025
  Workshop on Sustainable Space Robotics
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
github:
  is_project_page: false
